[package]
name = "cargo2pkg"
version = "0.1.0"
authors = ["Anton Whalley <anton@venshare.com>"]
edition = "2018"

[dependencies]
clap = "2.23.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4.10"
sha2 = "0.8.0"
hex = "0.3.2"
